### ISSUE TITLE
Throughput (MB/s)

### ISSUE THREAD

**Issue by mind-mind** [schrej/podmigration-operator#3]
Dear @schrej 

Can we get throughput from “kubectl migrate”? For example, if we use “scp”, it will have a throughput log. I would like to know that "kubectl migrate" can do that whether or not?

**Comment by schrej** [comment]
There is no `kubectl migrate` command, or at least I didn't implement one. While it would be possible to implement, it's probably a lot of work. It could work similar to how logs are fetched directly from kubelet on the node. My implementation also didn't use SCP but NFS as it is a lot faster.

**Comment by mind-mind** [comment]
Thanks
