### ISSUE TITLE
Connection between Pod

### ISSUE THREAD

**Issue by mind-mind** [schrej/podmigration-operator#5]
Hi,
I’m wonder that why pod migrating cannot migrate if the connection between node isn’t good enough?

**Comment by schrej** [comment]
In theory a slow connection shouldn't prevent a migration with the current strategy, it will just be slow and cause a lot of downtime, unless the Pod (or rather its containers) is very small.
Is it failing? Or is it just slow?

**Comment by mind-mind** [comment]
No, I just want to make sure that I understand correctly.

**Comment by mind-mind** [comment]
Thank you.

**Comment by mind-mind** [comment]
Anyway, how do you get downtime from migrating?

**Comment by schrej** [comment]
For my evaluation I ran a web server as a test workload and just pinged that to monitor the downtime. See here: https://github.com/schrej/podmigration-operator/blob/master/evaluation/eval.go
